/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PereiraFernando_Gradle;

import java.util.Scanner;
import org.apache.commons.lang3.StringUtils;

/*
Hecho por: Fernando José Pereira Salvador
1 DAM Presencial
EDD Proyecto Gradle
 */
public class App {

    public static void main(String[] args) {

        // Creditos
        System.out.println("Hecho por: Fernando José Pereira Salvador");
        System.out.println("1 DAM Presencial");
        System.out.println("EDD Proyecto Gradle");
        System.out.println();

        // Figura 1: Círculo
        System.out.println("Figura 1: Círculo");
        // Valor del radio
        double radio = 2;
        // Calculamos el area y mostramos resultados
        System.out.println("El radio es " + radio);
        double area = FiguraGeometrica.areaCirculo(radio);
        System.out.println("El área del círculo es: " + area);
        System.out.println();

        // Figura 2: Rectángulo
        System.out.println("Figura 2: Rectángulo");
        // Valor de la base
        double base = 3;
        // Valor de la altura
        double altura = 2;
        // Calculamos el area y mostramos resultados
        System.out.println("La base es " + base + " y la altura es " + altura);
        area = FiguraGeometrica.areaRectangulo(base, altura);
        System.out.println("El área del rectángulo es: " + area);
        System.out.println();

        // Figura 3: Triángulo
        System.out.println("Figura 3: Triángulo");
        // Valor de la base
        base = 4;
        // Valor de la altura
        altura = 3;
        // Calculamos el area y mostramos resultados
        System.out.println("El valor de la base es " + base + " y la altura es " + altura);
        area = FiguraGeometrica.areaTriangulo(base, altura);
        System.out.println("El área del triángulo es: " + area);
        System.out.println();

        // Figura 4: Cuadrado
        System.out.println("Figura 4: Cuadrado");
        // Valor del lado
        double lado = 4;
        // Calculamos el area del cuadrado y mostramos resultado
        System.out.println("El lado del cuadrado es " + lado);
        area = FiguraGeometrica.areaCuadrado(lado);
        System.out.println("El área del cuadrado es: " + area);
        System.out.println();

        // Figura 5: Trapecio
        System.out.println("Figura 5: Trapecio");
        // Valor de la base mayor
        double baseMayor = 5;
        // Valor de la base menor
        double baseMenor = 4;
        // Valor de la altura
        altura = 2;
        // Calculamos el area del trapecio y mostramos resultado
        System.out.println("La base mayor es " + baseMayor + ", la menor es " + baseMenor + " y la altura es " + altura);
        area = FiguraGeometrica.areaTrapecio(baseMayor, baseMenor, altura);
        System.out.println("El área del trapecio es: " + area);

    }
}
